# Generated by Django 4.2.11 on 2024-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('company_address', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
    ]
