# Generated by Django 4.2.11 on 2024-03-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_sitesetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSetting',
        ),
    ]
