# Generated by Django 4.2.11 on 2024-03-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
    ]
