# Generated by Django 4.2.11 on 2024-03-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0005_remove_category_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='机械名称')),
                ('category', models.CharField(max_length=64, verbose_name='类别')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=64, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
    ]
