# Generated by Django 4.2.11 on 2024-03-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0006_alter_category_category_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=0, upload_to='', verbose_name='产品图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industry.category', verbose_name='类别'),
        ),
    ]
