# Generated by Django 4.2.11 on 2024-03-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0007_product_product_image_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.TextField(blank=True, verbose_name='产品介绍'),
        ),
    ]
