# Generated by Django 4.2.11 on 2024-03-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0008_product_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='param_image',
            field=models.ImageField(default=0, upload_to='', verbose_name='参数图片'),
        ),
    ]
