# Generated by Django 4.2.11 on 2024-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0009_product_param_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='param_image',
            field=models.ImageField(default=0, upload_to='param_img/', verbose_name='参数图片'),
        ),
    ]
