# Generated by Django 4.2.11 on 2024-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0010_alter_product_param_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=64, verbose_name='手机号')),
                ('ipAddr', models.CharField(max_length=32, verbose_name='IP地址')),
                ('place', models.CharField(max_length=255, verbose_name='用户地址')),
                ('message', models.TextField(verbose_name='留言信息')),
            ],
        ),
    ]
