# Generated by Django 4.2.11 on 2024-03-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0011_leavemessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
